theme: jekyll-theme-primer
title: Homepage
description: Predicting the success of your playlist
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
