theme: jekyll-theme-architect
title: Spotify
description: Predicting the success of your playlist and providing personalized recommendations
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
