theme: jekyll-theme-architect
title: Spotify Group30
description: Predicting the success of your playlist and providing smart personalised recommendations
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
